const KEY_MATCHING = {
  'Kudos image': 'badgeImageLink',
  'Lesson image': 'lessonImageLink',
  'Lesson collected image': 'lessonCollectedImageLink',
  'Lesson collectible gif': 'lessonCollectibleGif',
  'Lesson collectible video': 'lessonCollectibleVideo',
  'Lesson collectible mint ID': 'lessonCollectibleMintID',
  'Lesson collectible token address': 'lessonCollectibleTokenAddress',
  'Social image': 'socialImageLink',
  'What will you be able to do after this lesson?': 'learningActions',
  'Landing page copy': 'marketingDescription',
  'Badge ID': 'badgeId',
  'DataDisk vector mint': 'datadiskVectorMint',
  'Collectible ID': 'collectibleId',
  'Duration in minutes': 'duration',
  'What will you learn from this?': 'learnings',
  Difficulty: 'difficulty',
  Description: 'description',
  Name: 'name',
  'Languages': 'languages',
  'Level': 'level',
  'Tags': 'tags',
  'Community': 'community',
  'Lesson Writers': 'lessonWriters',
  Module: 'moduleId',
  Quest: 'quest',
  'Quest Social Message': 'questSocialMessage',
  'Publication status': 'publicationStatus',
  'Publication Date': 'publicationDate',
  'Featured order on homepage': 'featuredOrderOnHomepage',
  'Enable Comments': 'isCommentsEnabled',
  'End of Lesson redirect': 'endOfLessonRedirect',
  'End of Lesson text': 'endOfLessonText',
  // 'Community discussion link': 'communityDiscussionLink',
  'Mirror link': 'mirrorLink',
  'Mirror NFT address': 'mirrorNFTAddress',
  'Mirror NFT all collected': 'areMirrorNFTAllCollected',
  'Sponsor Name': 'sponsorName',
  'Sponsor Logo': 'sponsorLogo',
  'NFT Gating': 'nftGating',
  'NFT Gating Requirements': 'nftGatingRequirements',
  'NFT Gating Image': 'nftGatingImageLink',
  'NFT Gating Link': 'nftGatingLink',
  'NFT Gating CTA': 'nftGatingCTA',
}

const LESSON_SPLITTER = `\`\`\`

---`

module.exports = {
  KEY_MATCHING,
  LESSON_SPLITTER,
};
