targets:
  - name: lessons
    sources:
      - /public/lesson/*.md
    file: /public/lesson/%language%.strings
    format: macosx
files:
  - source: /public/lesson/*.md
    translation: /translations/%two_letters_code%/%original_file_name%
  - source: /src/constants/lessons.ts
    translation: /src/constants/lessons_%two_letters_code%.ts
